name: "Deploy Vizion API (Hostinger)"

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Add Host to known_hosts"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.HOSTINGER_HOST }}" >> ~/.ssh/known_hosts

      - name: "Deploy via SSH"
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            APP_DIR="/root/vizion-api"

            echo "[1/4] Atualizando código"
            cd "$APP_DIR"
            git fetch --all --prune
            git reset --hard origin/main

            echo "[2/4] Instalando deps e build"
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
            npm run build

            echo "[3/4] Ciclo PM2"
            pm2 stop vizion-api || true
            pm2 delete vizion-api || true
            pm2 start ecosystem.config.js --only vizion-api --update-env
            pm2 save
